### ISSUE TITLE
Fails to build on PowerPC Mac with R 4.1.2

### ISSUE THREAD

**Issue by barracuda156** [tidyverse/vroom#385]
* installing *source* package ‘vroom’ ...
** package ‘vroom’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
/opt/local/bin/g++-mp-7  -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Imio/include -DWIN32_LEAN_AND_MEAN -Ispdlog/include -DFMT_HEADER_ONLY -I'/Users/svacchanda/Library/R/powerpc/4.1/library/progress/include' -I'/Users/svacchanda/Library/R/powerpc/4.1/library/cpp11/include' -I'/Users/svacchanda/Library/R/powerpc/4.1/library/tzdb/include' -I/opt/local/include     -pipe -Os -arch ppc -m32  -c Iconv.cpp -o Iconv.o
Iconv.cpp: In function 'SEXPREC* safeMakeChar(const char*, size_t, bool)':
Iconv.cpp:70:23: error: 'strnlen' was not declared in this scope
 #define readr_strnlen strnlen
                       ^
Iconv.cpp:76:24: note: in expansion of macro 'readr_strnlen'
   size_t m = hasNull ? readr_strnlen(start, n) : n;
                        ^~~~~~~~~~~~~
Iconv.cpp:70:23: note: suggested alternative: 'strlen'
 #define readr_strnlen strnlen
                       ^
Iconv.cpp:76:24: note: in expansion of macro 'readr_strnlen'
   size_t m = hasNull ? readr_strnlen(start, n) : n;
                        ^~~~~~~~~~~~~
make: *** [Iconv.o] Error 1
ERROR: compilation failed for package ‘vroom’

**Comment by jimhester** [comment]
The PowerPC mac has not been produced for 15 years. We unfortunately do not have the time or development resources to support it.

**Comment by barracuda156** [comment]
Maybe you could advise how to try fix that on my end, if the log
suggests something?

**Comment by jimhester** [comment]
probably adding `#include <string.h>` to that header.
